version: "3"

services:
  client:
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - '5500:5500'
    restart: 'unless-stopped'
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - /app/node_modules
      - /server/helpers/redis.js:/app/helper/redis

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'