name: Run Tests

on:
  push:
    branches: 
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.12.1

      - name: Install Dependencies on Server
        run: npm install
        working-directory: server
      
      - name: Run Tests
        run: npm test
        working-directory: server

      - name: Install Dependencies on Client
        run: npm install
        working-directory: client
      
      - name: Build Client
        run: CI="" npm run build
        working-directory: client
